name: Build and Push Docker Image with Buildpacks.io

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up pack CLI
        uses: docker/setup-buildx-action@v1
      - name: Install Pack CLI
        run: |
          add-apt-repository ppa:cncf-buildpacks/pack-cli
          apt-get update
          apt-get install pack-cli
      - name: Build app with Buildpacks.io and paketo-buildpacks
        run: pack build ohiani/test:latest --builder paketobuildpacks/builder:base --buildpacks paketobuildpacks/nodejs --buildpacks paketobuildpacks/nginx --path .
      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: your-docker-registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ohiani/test
